In [1]:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Looking in indexes: https://download.pytorch.org/whl/cu118
Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch
torch.__version__

'2.3.0+cu118'

### Random tensor

In [3]:
random_tensor=torch.rand(5,2,4)
random_tensor

tensor([[[0.2296, 0.3280, 0.0618, 0.8557],
         [0.7230, 0.7865, 0.8799, 0.7952]],

        [[0.0429, 0.5666, 0.3613, 0.3663],
         [0.3151, 0.0687, 0.5716, 0.2701]],

        [[0.0051, 0.2910, 0.4103, 0.0031],
         [0.1917, 0.1666, 0.1884, 0.5061]],

        [[0.7878, 0.5278, 0.4248, 0.4089],
         [0.8555, 0.6624, 0.3909, 0.5735]],

        [[0.6702, 0.4863, 0.6859, 0.2327],
         [0.1327, 0.8980, 0.2449, 0.5892]]])

In [4]:
random_tensor.ndim

3

## random image tensor

In [5]:
random_image_tensor=torch.rand(size= (3,113,113)) #Color channel,H,W
random_image_tensor.shape,random_image_tensor.ndim

(torch.Size([3, 113, 113]), 3)

## 0s and 1s tensors

In [6]:
#0s 
zeros=torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
#1s
ones=torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

### Creating a range and tensors like

In [8]:
range=torch.arange(1,11)
range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
zeroes_like=torch.zeros_like(range)
zeroes_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# datatype

In [10]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [11]:
float_16_tensor=float_32_tensor.type(torch.float16) # can use tensor.half
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [12]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

# Getting information from tensors

In [13]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.1018, 0.6948, 0.4201, 0.0618],
        [0.7601, 0.9262, 0.4583, 0.3053],
        [0.4915, 0.7142, 0.9622, 0.0436]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Manipulating tensors (tensor operations)


These operations are often a wonderful dance between:

1. Addition
2. Substraction
3. Multiplication (element-wise)
4. Division
5. Matrix multiplication

In [14]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [15]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [16]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [17]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [18]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [19]:
# Original tensor is still unchanged 
tensor

tensor([1, 2, 3])

In [20]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


# Matrix multiplication


In [21]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [22]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [23]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [24]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [25]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


# Finding the min, max, mean, sum, etc (aggregation)

In [26]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [27]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


# Positional min/max

In [28]:
print(f"Tensor: {x}")

# Returns index of max and min values
print(f"Index where max value occurs: {x.argmax()}")
print(f"Index where min value occurs: {x.argmin()}")

Tensor: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 9
Index where min value occurs: 0


# Reshaping, stacking, squeezing and unsqueezing

In [29]:
# Create a tensor

x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [30]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [32]:
# Change view (keeps same data as original but changes view)

z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [33]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [37]:
x_stacked = torch.stack([x, x, x, x], dim=0) #dim=0
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [38]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) #dim=1
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])